version: "3.8"

services:
  postgres:
    container_name: microservices-ddd
    image: "bitnami/postgresql"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DATABASE: ms
